version: '3'

services:
  flask-api:
    image: in1t3r/testapi:debian
    environment:
      DATABASE_URL: postgresql://apiuser:password@postgres:5432/apidb
      FLASK_ENV: development
    links:
      - postgres
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=apiuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=apidb

volumes:
  postgres_data:
