version: '3'

services:
  flask-api:
    image: in1t3r/testapi:debian
    environment:
      DATABASE_URL: mysql+pymysql://apiuser:password@mysql/apidb
    links:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'apidb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'apiuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: