service: flaskapi

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-central-1
  memorySize: 128
  environment:
    S3SQLite_bucket: s3sqlitebucket

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.app
    packRequirements: false

package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

