"""fullname requirement

Revision ID: 21cfe7a4dc23
Revises: 34c50313254d
Create Date: 2019-12-28 10:51:28.415037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cfe7a4dc23'
down_revision = '34c50313254d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
